name: UNNKONET
description: A News App abstracted from unnkonet.com.ng
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  webview_flutter: ^0.3.15+1
  provider: any
  url_launcher: any
  cached_network_image: any
  sqflite: any
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  video_player: ^0.10.8+1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Digiface
      fonts:
        - asset: assets/fonts/digifaw.ttf
          weight: 700

    - family: lucida1
      fonts:
        - asset: assets/fonts/lucida1.ttf
          weight: 700
    - family: ftf
      fonts:
        - asset: assets/fonts/ftf.ttf
          weight: 500
    - family: lfax
      fonts:
        - asset: assets/fonts/lfax.ttf
          weight: 500
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
